from detectron2.config import CfgNode as CN


def add_dcl_config(cfg):
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS = CN()
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.LOSS_WEIGHT = 1.2
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.NUM_SAMPLES = 32
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.TEMPERATURE = 0.07
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.WITH_PROJ = True
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.MAX_INSTANCES = 100
    cfg.MODEL.ROI_MASK_HEAD.CONTRAST_LOSS.LOSS_FUNC = 'dense_contrast_loss'
